name: Docker Build and Push

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - uses: docker/setup-buildx-action@v3
    - uses: gittools/actions/gitversion/setup@v4
      with:
        versionSpec: '6.x'
    - uses: gittools/actions/gitversion/execute@v4
    - run: |
        IMAGE_ID=freeesia/cache-ogp
        IMAGE_ID=${IMAGE_ID,,}
        echo "image_tag=$IMAGE_ID" >> $GITHUB_ENV
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v6
      with:
        context: .
        build-args: |
          Repository=${{ github.repository }}
          Version=${{ env.GitVersion_FullSemVer }}
          AssemblyVersion=${{ env.GitVersion_AssemblySemVer }}
          FileVersion=${{ env.GitVersion_AssemblySemFileVer }}
          InformationalVersion=${{ env.GitVersion_InformationalVersion }}
        labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
        push: ${{ github.ref_name == 'main' }}
        tags: ghcr.io/${{ env.image_tag }}:${{ env.GitVersion_FullSemVer }},ghcr.io/${{ env.image_tag }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
